# match black
line-length = 79
target-version = "py310"
[lint]
select = ["E", "F", "SIM", "N", "I", "B"]

[format]
line-ending = "lf"
docstring-code-line-length = "dynamic"

[lint.flake8-unused-arguments]
ignore-variadic-names = true
