"""updated Service model

Revision ID: 20080d993e20
Revises: df478cd71cd9
Create Date: 2025-08-05 09:56:37.544148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision = '20080d993e20'
down_revision = 'df478cd71cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # NOTE: The problematic column drops and alterations have been stripped out.
    
    # These columns are new and need to be added:
    op.add_column('services', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('services', sa.Column('place', sa.Boolean(), nullable=True))
    op.add_column('services', sa.Column('delivery', sa.Boolean(), nullable=True))
    op.add_column('services', sa.Column('requires_booking', sa.Boolean(), nullable=True))
    
    op.create_index(op.f('ix_services_location'), 'services', ['location'], unique=False)
    
    # op.drop_column('services', 'type_id') is removed as it's the source of the UndefinedColumn error.
    
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'services', type_='foreignkey')
    # This create_foreign_key in downgrade might need adjustment if the table it points to doesn't exist.
    # For now, we focus on the upgrade path.
    op.create_foreign_key('services_type_id_fkey', 'services', 'service_types', ['type_id'], ['id'])
    op.drop_index(op.f('ix_services_location'), table_name='services')
    op.drop_column('services', 'requires_booking')
    op.drop_column('services', 'delivery')
    op.drop_column('services', 'place')
    op.drop_column('services', 'location')
    op.drop_column('services', 'category_id')
    op.add_column('memory', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_memory_id'), table_name='memory')
    op.alter_column('memory', 'id',
                   existing_type=sa.Uuid(),
                   type_=sa.INTEGER(),
                   existing_nullable=False)
    op.create_table('service_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='service_types_pkey'),
    sa.UniqueConstraint('name', name='service_types_name_key')
    )
    op.drop_index(op.f('ix_service_categories_name'), table_name='service_categories')
    op.drop_table('service_categories')
    # ### end Alembic commands ###
