"""create memory table

Revision ID: 87154e32ee38
Revises: 58916f4895c7
Create Date: 2025-07-28 14:13:51.870486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87154e32ee38'
down_revision = '58916f4895c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
