"""add business name field

Revision ID: 8b7af948bf55
Revises: 5188720acd4d
Create Date: 2025-07-29 09:21:45.538478

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8b7af948bf55'
down_revision = '5188720acd4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('business_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'business_name')
    # ### end Alembic commands ###
