"""create memory table

Revision ID: 8cf30a8110ba
Revises: 87154e32ee38
Create Date: 2025-07-28 14:22:05.281464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf30a8110ba'
down_revision = '87154e32ee38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
