"""empty message

Revision ID: 8efcc04ad2af
Revises: 20080d993e20
Create Date: 2025-08-05 15:20:12.377606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8efcc04ad2af'
down_revision = '20080d993e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
