

"""Added full_name to booking table

Revision ID: e5fc093c2709
Revises: 8b7af948bf55
Create Date: 2025-07-30 09:24:01.194766

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel 

# revision identifiers, used by Alembic.
revision = 'e5fc093c2709'
down_revision = '8b7af948bf55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_bookings_full_name'), 'bookings', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_full_name'), table_name='bookings')
    op.drop_column('bookings', 'full_name')
    # ### end Alembic commands ###
